name: Run Python Data Script Monthly

on:
  schedule:
    - cron: "0 12 26 * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      DB1_HOST: ${{ secrets.DB1_HOST }}
      DB1_NAME: ${{ secrets.DB1_NAME }} 
      DB1_USER: ${{ secrets.DB1_USER }} 
      DB1_PASS: ${{ secrets.DB1_PASS }}
      DB1_PORT: ${{ secrets.DB1_PORT }}

      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run script
        run: python choose_a_model.py
        timeout-minutes: 360

